<?php  
  "page_profil_title":             "Mon profil", 
  "page_profil_title_settings":    "Paramètres", 
  "page_profil_title_tasks":       "Mes tâches", 
  "page_profil_title_change_pass": "Sécurité", 
  "page_profil_title_presentation":"Informations", 
  "page_profil_full_name":         "Nom complet", 
  "page_profil_login":             "Identifiant", 
  "page_profil_role":              "Rôle", 
  "page_profil_name":              "Nom", 
  "page_profil_firstname":         "Prénom", 
  "page_profil_gender":            "Genre", 
  "page_profil_female":            "Femme", 
  "page_profil_male":              "Homme", 
  "page_profil_email":             "Email", 
  "page_profil_address1":          "Adresse", 
  "page_profil_address2":          "Complément", 
  "page_profil_country":           "Pays", 
  "page_profil_zip_code":          "Code postal", 
  "page_profil_city":              "Ville", 
  "page_profil_emailBackup":       "Email de secours", 
  "page_profil_date_of_birth":     "Date d'anniversaire", 
  "page_profil_phone":             "Téléphone", 
  "page_profil_mobile":            "Portable", 
  "page_profil_langue":            "Langue", 
  "page_profil_photo_profil":      "Changer ma photo de profil", 
  "page_profil_notifier":          "J'accepte de recevoir des courriels de notifications", 
  "page_profil_social_links":      "Mes réseaux sociaux", 
  "page_profil_edit_settings":     "Modifier vos paramètres personnels", 
  "page_profil_update_title":      "Modifier mon profil", 
  
  "page_profil_title_2":           "Changer mon mot de passe", 
  "page_profil_old_pass":          "Ancien mot de passe", 
  "page_profil_new_pass":          "Nouveau mot de passe", 
  "page_profil_confirm_pass":      "Confirmer le mot de passe", 
  "page_profil_change_pass_title": "Changer mon mot de passe", 
  
  "page_nutrition_my_diet_title":                 "Mes diètes en cours", 
  "page_nutrition_my_diet_name":                  "Nom diète", 
  "page_nutrition_my_diet_assigned_for":          "Prénom Nom", 
  "page_nutrition_my_diet_list_assigned_for_one": "Elève", 
  "page_nutrition_my_diet_list_assigned_for_plur":"Elèves", 
  "page_nutrition_my_diet_duration":              "Durée", 
  "page_nutrition_my_diet_date_begin":            "Date de début", 
  "page_nutrition_my_diet_add_date_begin":        "Sélectionnez une date de début", 
  "page_nutrition_my_diet_date_end":              "Date de fin", 
  "page_nutrition_my_diet_tags":                  "Tags", 
  "page_nutrition_my_diet_add_tag":               "Ajouter un tag", 
  "page_nutrition_my_diet_advancement":           "Avancement", 
  "page_nutrition_my_diet_add_title":             "Ajouter une diète", 
  "page_nutrition_my_diet_update_title":          "Modifier la diète", 
  "page_nutrition_my_diet_delete_title":          "Supprimer la diète", 
  "page_nutrition_my_diet_restore_title":         "Restaurer la diète", 

  "page_nutrition_my_template_diet_title":                 "Mes templates de diètes", 
  "page_nutrition_my_template_diet_name":                  "Nom diète", 
  "page_nutrition_my_template_diet_assigned_for":          "Nombre d'élèves assignés", 
  "page_nutrition_my_template_diet_duration":              "Durée", 
  "page_nutrition_my_template_diet_tags":                  "Tags", 
  "page_nutrition_my_template_diet_add_tag":               "Ajouter un tag", 
  "page_nutrition_my_template_diet_advancement":           "Avancement", 
  "page_nutrition_my_template_diet_add_title":             "Ajouter une diète", 
  "page_nutrition_my_template_diet_update_title":          "Modifier la diète", 
  "page_nutrition_my_template_diet_delete_title":          "Supprimer la diète", 
  "page_nutrition_my_template_diet_restore_title":         "Restaurer la diète", 

  "page_nutrition_my_recipe_title":                 "Mes recettes", 
  "page_nutrition_my_recipe_picture":               "Image", 
  "page_nutrition_my_recipe_name":                  "Nom", 
  "page_nutrition_my_recipe_nutritional_info":      "Informations nutritionelles", 
  "page_nutrition_my_recipe_notes":                 "Notes", 
  "page_nutrition_my_recipe_add_title":             "Ajouter une diète", 
  "page_nutrition_my_recipe_update_title":          "Modifier la diète", 
  "page_nutrition_my_recipe_delete_title":          "Supprimer la diète", 
  "page_nutrition_my_recipe_restore_title":         "Restaurer la diète", 

  "page_food_food_title":         "Liste des aliments", 
  "page_food_food_name":          "Nom", 
  "page_food_food_brand":         "Marque", 
  "page_food_food_labels":        "Labels", 
  "page_food_food_categories":    "Catégories", 
  "page_food_food_nutritionals":  "Informations nutritionnelles", 
  "page_food_food_weight":        "Taille", 
  "page_food_food_weight_type":   "Contenance", 
  "page_food_food_weights":       "Tailles", 
  "page_food_food_score_nutri":   "Scrore Nutri", 
  "page_food_food_score_nova":    "Scrore Nova", 
  "page_food_food_score_eco":     "Scrore Eco", 
  "page_food_food_picture":       "Image", 
  "page_food_food_status":        "Statut", 
  "page_food_food_action":        "Actions", 
  "page_food_food_add_title":     "Ajouter un aliment", 
  "page_food_food_update_title":  "Modifier l'aliment", 
  "page_food_food_delete_title":  "Supprimer l'aliment", 
  "page_food_food_restore_title": "Restaurer l'aliment", 
  
  "page_food_food_add_labels":          "Ajouter un label", 
  "page_food_food_update_labels":       "Modifier un label", 
  "page_food_food_delete_labels":       "Supprimer un label", 
  "page_food_food_add_categories":      "Ajouter une catégorie", 
  "page_food_food_update_categories":   "Modifier une catégorie", 
  "page_food_food_delete_categories":   "Supprimer une catégorie", 
  "page_food_food_add_nutritionals":    "Ajouter une information nutritionnelle", 
  "page_food_food_update_nutritionals": "Modifier une information nutritionnelle", 
  "page_food_food_delete_nutritionals": "Supprimer une information nutritionnelle", 
  "page_food_food_add_weight":          "Ajouter une taille", 
  "page_food_food_update_weight":       "Modifier une taille", 
  "page_food_food_delete_weight":       "Supprimer une taille", 
  

  "page_food_brand_title":         "Liste des marques", 
  "page_food_brand_picture":       "Image", 
  "page_food_brand_code":          "Code", 
  "page_food_brand_name":          "Nom", 
  "page_food_brand_status":        "Statut", 
  "page_food_brand_action":        "Actions", 
  "page_food_brand_add_title":     "Ajouter une marque", 
  "page_food_brand_update_title":  "Modifier la marque", 
  "page_food_brand_delete_title":  "Supprimer la marque", 
  "page_food_brand_restore_title": "Restaurer la marque", 

  "page_food_eco_score_title":         "Liste des éco scores", 
  "page_food_eco_score_picture":       "Image", 
  "page_food_eco_score_code":          "Code", 
  "page_food_eco_score_name":          "Nom", 
  "page_food_eco_score_color":         "Couleur", 
  "page_food_eco_score_status":        "Statut", 
  "page_food_eco_score_action":        "Actions", 
  "page_food_eco_score_add_title":     "Ajouter un éco score", 
  "page_food_eco_score_update_title":  "Modifier l'éco score", 
  "page_food_eco_score_delete_title":  "Supprimer l'éco score", 
  "page_food_eco_score_restore_title": "Restaurer l'éco score", 

  "page_food_label_title":         "Liste des labels", 
  "page_food_label_picture":       "Image", 
  "page_food_label_code":          "Code", 
  "page_food_label_name":          "Nom", 
  "page_food_label_color":         "Couleur", 
  "page_food_label_status":        "Statut", 
  "page_food_label_action":        "Actions", 
  "page_food_label_add_title":     "Ajouter un label", 
  "page_food_label_update_title":  "Modifier le label", 
  "page_food_label_delete_title":  "Supprimer le label", 
  "page_food_label_restore_title": "Restaurer le label", 

  "page_food_nova_score_title":           "Liste des nova scores", 
  "page_food_nova_score_picture":         "Image", 
  "page_food_nova_score_code":            "Code", 
  "page_food_nova_score_name":            "Nom", 
  "page_food_nova_score_color":           "Couleur", 
  "page_food_nova_score_status":          "Statut", 
  "page_food_nova_score_action":          "Actions", 
  "page_food_nova_score_add_title":       "Ajouter un nova score", 
  "page_food_nova_score_update_title":    "Modifier le nova score", 
  "page_food_nova_score_delete_title":    "Supprimer le nova score", 
  "page_food_nova_score_restore_title":   "Restaurer le nova score", 

  "page_food_nutri_score_title":          "Liste des nutri scores", 
  "page_food_nutri_score_picture":        "Image", 
  "page_food_nutri_score_code":           "Code", 
  "page_food_nutri_score_name":           "Nom", 
  "page_food_nutri_score_color":          "Couleur", 
  "page_food_nutri_score_status":         "Statut", 
  "page_food_nutri_score_action":         "Actions", 
  "page_food_nutri_score_add_title":      "Ajouter un nutri score", 
  "page_food_nutri_score_update_title":   "Modifier le nutri score", 
  "page_food_nutri_score_delete_title":   "Supprimer le nutri score", 
  "page_food_nutri_score_restore_title":  "Restaurer le nutri score", 

  "page_codeTables_language_title":         "Liste des langues", 
  "page_codeTables_language_picture":       "Image", 
  "page_codeTables_language_code":          "Code", 
  "page_codeTables_language_name":          "Nom", 
  "page_codeTables_language_status":        "Statut", 
  "page_codeTables_language_action":        "Actions", 
  "page_codeTables_language_add_title":     "Ajouter une langue", 
  "page_codeTables_language_update_title":  "Modifier la langue", 
  "page_codeTables_language_delete_title":  "Supprimer la langue", 
  "page_codeTables_language_restore_title": "Restaurer la langue", 

  "page_codeTables_weight_type_title":          "Liste des unités de mesures", 
  "page_codeTables_weight_type_code":           "Code", 
  "page_codeTables_weight_type_name":           "Nom", 
  "page_codeTables_weight_type_abbreviation":   "Abbréviation", 
  "page_codeTables_weight_type_language":       "Langue", 
  "page_codeTables_weight_type_description":    "Description", 
  "page_codeTables_weight_type_type":           "Type", 
  "page_codeTables_weight_type_status":         "Statut", 
  "page_codeTables_weight_type_action":         "Actions", 
  "page_codeTables_weight_type_add_title":      "Ajouter une unité de mesures", 
  "page_codeTables_weight_type_update_title":   "Modifier l'unité de mesures", 
  "page_codeTables_weight_type_delete_title":   "Supprimer l'unité de mesures", 
  "page_codeTables_weight_type_restore_title":  "Restaurer l'unité de mesures", 
  "page_codeTables_weight_type_solid_title":    "Solide", 
  "page_codeTables_weight_type_liquid_title":   "Liquide", 
  "page_codeTables_weight_type_other_title":    "Autre", 

  "page_codeTables_nutritional_title":          "Liste des informations nutritionnelles", 
  "page_codeTables_nutritional_code":           "Code", 
  "page_codeTables_nutritional_name":           "Nom", 
  "page_codeTables_nutritional_language":       "Langue", 
  "page_codeTables_nutritional_status":         "Statut", 
  "page_codeTables_nutritional_action":         "Actions", 
  "page_codeTables_nutritional_add_title":      "Ajouter une information nutritionnelle", 
  "page_codeTables_nutritional_update_title":   "Modifier l'information nutritionnelle", 
  "page_codeTables_nutritional_delete_title":   "Supprimer l'information nutritionnelle", 
  "page_codeTables_nutritional_restore_title":  "Restaurer l'information nutritionnelle", 

  "page_codeTables_food_category_title":        "Liste des catégories d'aliments", 
  "page_codeTables_food_category_code":         "Code", 
  "page_codeTables_food_category_name":         "Nom", 
  "page_codeTables_food_category_language":     "Langue", 
  "page_codeTables_food_category_status":       "Statut", 
  "page_codeTables_food_category_action":       "Actions", 
  "page_codeTables_food_category_add_title":    "Ajouter une catégorie d'aliment", 
  "page_codeTables_food_category_update_title": "Modifier la catégorie d'aliment", 
  "page_codeTables_food_category_delete_title": "Supprimer la catégorie d'aliment", 
  "page_codeTables_food_category_restore_title":"Restaurer la catégorie d'aliment", 

  "go":      "J'y vais !", 

  "page_all_close":           "Fermer", 
  "page_all_add":             "Ajouter", 
  "page_all_update":          "Modifier", 
  "page_all_initPass":        "Initialiser le mot de passe", 
  "page_all_view":            "Voir", 
  "page_all_delete":          "Supprimer", 
  "page_all_restore":         "Restaurer", 
  "page_all_yes":             "OUI", 
  "page_all_no":              "NON", 
  "page_all_change_picture":  "Changer l'image", 

  "confirm_delete"  : "Confirmez la suppression pour ",
  "confirm_restore" : "Confirmez la restoration pour ",

  "errorData_login_ko":         "Erreur de connexion, nom d'utilisateur ou mot de passe invalide !", 
  "errorData_ok":               "Traitement réussi !", 
  "errorData_ok_txt":           "Vos données ont été enregistrées avec succès.", 
  "errorData_ko":               "Erreur de traitement !", 
  "errorData_txt":              "Une erreur interne s'est produite !!", 
  "errorData_txt_code":         "Le code est manquant !!", 
  "errorData_txt_name":         "Le nom est manquant !!",
  "errorData_txt_description":  "La description est manquante !!",
  "errorData_txt_abbreviation": "L'abbréviation est manquante !!",
  "errorData_txt_weight":       "La taille est manquante !!",
  "errorData_txt_assignedUsers":"Aucun utilisateurs n'a été selectionné !!",
  "errorData_txt_duration":     "La durée est manquante !!",
  "errorData_txt_date_start":   "La date de début est manquante !!",
  
  "footer_signature": "WebVysion"
}