<?php
if (!defined('DISTRIX_APITOKEN_GENERATION_DATA_NAME')) {
  define("DISTRIX_APITOKEN_GENERATION_DATA_NAME", "tokenData");
}
if (!defined('DISTRIX_APITOKEN_VERIFY_DATA')) {
  define("DISTRIX_APITOKEN_VERIFY_DATA", "DISTRIX_APITOKEN_VERIFY_DATA");
}
if (!defined('DISTRIX_APITOKEN_VERIFY_RESULT')) {
  define("DISTRIX_APITOKEN_VERIFY_RESULT", "DISTRIX_APITOKEN_VERIFY_RESULT");
}
if (!defined('DISTRIX_APITOKEN_ERROR')) {
  define("DISTRIX_APITOKEN_ERROR", "DISTRIX_APITOKEN_ERROR");
}
if (!defined('DISTRIX_APITOKEN_CLIENT_ID_UNKNOWN')) {
  define("DISTRIX_APITOKEN_CLIENT_ID_UNKNOWN", "DISTRIX_APITOKEN_CLIENT_ID_UNKNOWN");
}
if (!defined('DISTRIX_APITOKEN_NO_TRANSACTION')) {
  define("DISTRIX_APITOKEN_NO_TRANSACTION", "DISTRIX_APITOKEN_NO_TRANSACTION");
}
if (!defined('DISTRIX_APITOKEN_COMMIT')) {
  define("DISTRIX_APITOKEN_COMMIT", "DISTRIX_APITOKEN_COMMIT");
}
if (!defined('DISTRIX_APITOKEN_ROLLBACK')) {
  define("DISTRIX_APITOKEN_ROLLBACK", "DISTRIX_APITOKEN_ROLLBACK");
}
if (!defined('DISTRIX_APITOKEN_NO_DATABASE_CONNECTION')) {
  define("DISTRIX_APITOKEN_NO_DATABASE_CONNECTION", "DISTRIX_APITOKEN_NO_DATABASE_CONNECTION");
}
if (!defined('DISTRIX_APITOKEN_GENERATION_UNAVAILABLE')) {
  define("DISTRIX_APITOKEN_GENERATION_UNAVAILABLE", "DISTRIX_APITOKEN_GENERATION_UNAVAILABLE");
}
if (!defined('DISTRIX_APITOKEN_INVALID')) {
  define("DISTRIX_APITOKEN_INVALID", "DISTRIX_APITOKEN_INVALID");
}
