<?php
// Service name 
if (!defined('DISTRIX_DEPLOYER_SERVICES')) {
  define("DISTRIX_DEPLOYER_SERVICES", 'DISTRIX_DEPLOYER_SERVICES');
}
// Service modules
if (!defined('DISTRIX_DEPLOYER_GET_FROM')) {
  define("DISTRIX_DEPLOYER_GET_FROM", 'DISTRIX_DEPLOYER_GET_FROM');
}
if (!defined('DISTRIX_DEPLOYER_SEND_TO')) {
  define("DISTRIX_DEPLOYER_SEND_TO", 'DISTRIX_DEPLOYER_SEND_TO');
}
// File list empty
if (!defined('DISTRIX_DEPLOYER_FILE_LIST_EMPTY_CODE')) {
  define("DISTRIX_DEPLOYER_FILE_LIST_EMPTY_CODE", 'DISTRIX_DEPLOYER_FILE_LIST_EMPTY');
}
if (!defined('DISTRIX_DEPLOYER_FILE_LIST_EMPTY_TXT')) {
  define("DISTRIX_DEPLOYER_FILE_LIST_EMPTY_TXT", 'The file list is empty.');
}
// File not found 
if (!defined('DISTRIX_DEPLOYER_FILE_NOT_FOUND_CODE')) {
  define("DISTRIX_DEPLOYER_FILE_NOT_FOUND_CODE", 'DISTRIX_DEPLOYER_FILE_NOT_FOUND');
}
if (!defined('DISTRIX_DEPLOYER_FILE_NOT_FOUND_TXT')) {
  define("DISTRIX_DEPLOYER_FILE_NOT_FOUND_TXT", 'The file has not been found.');
}
// Unable to copy for backup
if (!defined('DISTRIX_DEPLOYER_BAD_COPY_FILENAME_CODE')) {
  define("DISTRIX_DEPLOYER_BAD_COPY_FILENAME_CODE", 'DISTRIX_DEPLOYER_BAD_COPY_FILENAME');
}
if (!defined('DISTRIX_DEPLOYER_BAD_COPY_FILENAME_TEXT')) {
  define("DISTRIX_DEPLOYER_BAD_COPY_FILENAME_TEXT", 'The copy for backup file did not work :');
}
// Unable to save
if (!defined('DISTRIX_DEPLOYER_BAD_FILENAME_CODE')) {
  define("DISTRIX_DEPLOYER_BAD_FILENAME_CODE", 'DISTRIX_DEPLOYER_BAD_FILENAME');
}
if (!defined('DISTRIX_DEPLOYER_BAD_FILENAME_TEXT')) {
  define("DISTRIX_DEPLOYER_BAD_FILENAME_TEXT", 'The following filename is not correct :');
}
