<?php // Needed to encode in UTF8 ààéàé //
if (!defined('DISTRIX_SVC_VERSION')) {
  define("DISTRIX_SVC_VERSION",  "1.01");
}
if (!defined('DISTRIX_SVC_SERVICE_LEVEL')) {
  // define("DISTRIX_SVC_SERVICE_LEVEL", "../Services/");
  define("DISTRIX_SVC_SERVICE_LEVEL", "../../");
}
if (!defined('DISTRIX_INTERNAL_SVC_SERVICE_LEVEL')) {
  define("DISTRIX_INTERNAL_SVC_SERVICE_LEVEL", "../");
}
if (!defined('DISTRIX_SVC_RESPONSE_SERVICE_NAME_JSON_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_SERVICE_NAME_JSON_PARAMETER", "API_ServiceName");
}
if (!defined('DISTRIX_SVC_RESPONSE_SERVICE_NAME_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_SERVICE_NAME_PARAMETER", "DISTRIX_SVC_SVC");
}
if (!defined('DISTRIX_SVC_RESPONSE_METHOD_NAME_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_METHOD_NAME_PARAMETER", "DISTRIX_SVC_MET");
}
if (!defined('DISTRIX_SVC_RESPONSE_APITOKEN_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_APITOKEN_PARAMETER", "DISTRIX_SVC_APITOKEN");
}
if (!defined('DISTRIX_SVC_RESPONSE_SECRET_KEY_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_SECRET_KEY_PARAMETER", "DISTRIX_SVC_SCP");
}
if (!defined('DISTRIX_SVC_RESPONSE_LAYER_DATA_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_LAYER_DATA_PARAMETER", "DISTRIX_SVC_LDS");
}
if (!defined('DISTRIX_SVC_RESPONSE_DEBUG_MODE_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_DEBUG_MODE_PARAMETER", "DISTRIX_SVC_DBM");
}
if (!defined('DISTRIX_SVC_RESPONSE_DEBUG_INFO_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_DEBUG_INFO_PARAMETER", "DISTRIX_SVC_DBI");
}
if (!defined('DISTRIX_SVC_RESPONSE_ERROR')) {
  define("DISTRIX_SVC_RESPONSE_ERROR", "DISTRIX_SVC_RESPONSE_ERROR");
}
if (!defined('DISTRIX_SVC_RESPONSE_SECURITY_DATA_PARAMETER')) {
  define("DISTRIX_SVC_RESPONSE_SECURITY_DATA_PARAMETER", "DISTRIX_SVC_SDP");
}
if (!defined('DISTRIX_SVC_NO_LAYER_NOT_IN_DEBUG_MODE')) {
  define("DISTRIX_SVC_NO_LAYER_NOT_IN_DEBUG_MODE", 0);
}
if (!defined('DISTRIX_SVC_BUS_LAYER_IN_DEBUG_MODE')) {
  define("DISTRIX_SVC_BUS_LAYER_IN_DEBUG_MODE", 1);
}
if (!defined('DISTRIX_SVC_DATA_LAYER_IN_DEBUG_MODE')) {
  define("DISTRIX_SVC_DATA_LAYER_IN_DEBUG_MODE", 2);
}
if (!defined('DISTRIX_SVC_ALL_LAYERS_IN_DEBUG_MODE')) {
  define("DISTRIX_SVC_ALL_LAYERS_IN_DEBUG_MODE", 3);
}
if (!defined('DISTRIX_SVC_BUS_DEBUG')) {
  define("DISTRIX_SVC_BUS_DEBUG", "DISTRIX_SVC_BUS_DEBUG");
}
if (!defined('DISTRIX_SVC_DATA_DEBUG')) {
  define("DISTRIX_SVC_DATA_DEBUG", "DISTRIX_SVC_DATA_DEBUG");
}
if (!defined('DISTRIX_SVC_ERROR_CALLER')) {
  define("DISTRIX_SVC_ERROR_CALLER", "DISTRIX_SVC_ERROR_CALLER");
}
if (!defined('DISTRIX_SVC_ERROR_RESPONSE')) {
  define("DISTRIX_SVC_ERROR_RESPONSE", "DISTRIX_SVC_ERROR_RESPONSE");
}
if (!defined('DISTRIX_SVC_ERROR_CURL_INIT')) {
  define("DISTRIX_SVC_ERROR_CURL_INIT", "DISTRIX_SVC_ERROR_CURL_INIT");
}
if (!defined('DISTRIX_SVC_ERROR_SERVER_ADDRESS')) {
  define("DISTRIX_SVC_ERROR_SERVER_ADDRESS", "DISTRIX_SVC_ERROR_SERVER_ADDRESS");
}
if (!defined('DISTRIX_SVC_ERROR_CALLER_NAME')) {
  define("DISTRIX_SVC_ERROR_CALLER_NAME", "DISTRIX_SVC_ERROR_CALLER_NAME");
}
if (!defined('DISTRIX_SVC_ERROR_DATA_VALUE')) {
  define("DISTRIX_SVC_ERROR_DATA_VALUE", "DISTRIX_SVC_ERROR_DATA_VALUE");
}
